CEOS-Developers/CEOS-FE

- apps/ceos/src/assets/logo/index.tsx
- apps/ceos/src/components/FAQBox/index.tsx
- apps/ceos/src/components/Header/index.tsx
- apps/ceos/src/pages/index.tsx
#22 
전체적인 디자인 사이즈 수정 사항을 반영했습니다.
> refactor : 헤더, FAQ box 수정 사항 반영

- apps/ceos/src/pages/index.tsx
- packages/ui/src/components/Card/ManagementCard.tsx
- packages/ui/src/components/Card/ProjectCard.tsx
- packages/ui/src/components/Card/RewardCard.tsx
- packages/ui/src/components/Card/SponsorCard.tsx
- packages/ui/src/components/common/Text.tsx
#22 
#26 에 회짱님이 남겨주신 리뷰를 참고하여 Text의 color props를 한번에 받는 것으로 변경하였습니다.
원래는 `import React from 'react';` 요 구문없이도 에러가 안 났는데,
이젠 에러가 나네요...? 왜 이럴까요 ㅎ
> refactor: Text 팔레트컬러 props 통합

- .pnp.cjs
- apps/ceos/src/pages/project/index.tsx
- package.json
- packages/utils/index.tsx
- packages/utils/package.json
- packages/utils/src/apis/admin/loginApi.tsx
- packages/utils/src/apis/axiosConfig.ts
- packages/utils/src/apis/ceos/projectApi.tsx
- packages/utils/src/apis/index.ts
- yarn.lock
#4
- api 통신을 위한 axios & react-query 세팅
- ceos 페이지 내 GET project api 예시 샘플 작성 
-> data 인터페이스 추가 작업 필요
- admin 페이지에서 로그인 시 header에 access token을 추가하는 로직 작성
-> refresh token으로 새로운 access token 받아오는 로직 추가 필요
> feat: axios & react-query 세팅

- apps/ceos/src/assets/Diamond.tsx
- apps/ceos/src/components/Shortcut/index.tsx
- apps/ceos/src/pages/index.tsx
- packages/ui/src/styles/glass.tsx
- packages/ui/src/styles/typo.tsx
#3 
(1) 글라스 바로가기 버튼 1
(2) 글라스 바로가기 버튼 2
(1) 글라스 바로가기 버튼 1
(2) 글라스 바로가기 버튼 2
* pc버전 글라스 바로가기 버튼 2 처럼 줄바꿈이 필요한경우 그냥 <br/> 태그 쓰면 됩니다!
> feat: 글라스 바로가기 버튼 구현

- .pnp.cjs
- apps/admin/package.json
- apps/admin/src/components/Sidebar/index.tsx
- apps/admin/src/pages/_app.tsx
- apps/admin/src/pages/faq/index.tsx
- apps/ceos/package.json
- apps/ceos/src/assets/header/menuBtn.tsx
- apps/ceos/src/components/Title/index.tsx
- apps/ceos/src/pages/_app.tsx
- apps/ceos/src/pages/activity/index.tsx
- apps/ceos/src/pages/project/index.tsx
- packages/ui/src/assets/Arrow/index.tsx
- packages/ui/src/assets/CloseIcon/index.tsx
- packages/ui/src/assets/FloatingButton/Email/index.tsx
- packages/ui/src/assets/FloatingButton/Instagram/index.tsx
- packages/ui/src/assets/RewardCheck/index.tsx
- packages/ui/src/components/Card/ManagementCard.tsx
- packages/utils/src/apis/admin/faqApi.tsx
- packages/utils/src/apis/admin/index.ts
- packages/utils/src/apis/axiosConfig.ts
- packages/utils/src/apis/ceos/activityApi.tsx
- packages/utils/src/apis/ceos/index.ts
- packages/utils/src/apis/ceos/projectApi.tsx
- packages/utils/src/apis/index.ts
- yarn.lock
- #4 
- map에서 `key`가 누락된 워닝, svg-react 속성 호환성 문제로 발생하는 워닝 몇 가지를 수정했습니다.
- 무한 스크롤에 필요한 infiniteQuery의 경우 선언은 해두었지만 다음 페이지를 불러오는 `getNextPageParam`의 내부는 구현하지 않았으니 각 페이지 담당자분이 틀만 참고하고 내부로직 구현하시면 될 것 같습니다.
- 로그인 담당자분이 로그인 후 token 심는 로직 추가하시면 될 것 같습니다.
- 이상한 부분이 있다면 꼭 코멘트 남겨주세요,,,🥹
> feat: React Query 설정

- apps/admin/src/pages/application/index.tsx
- apps/admin/src/pages/faq/index.tsx
- apps/admin/src/pages/index.tsx
- apps/admin/src/pages/recruit/index.tsx
없음
- admin 페이지에서 mobile gap을 추가했습니다.
- 메인 페이지는 비어있어서 그냥 지원현황 페이지로 이동할 수 있도록 redirect를 추가했습니다
> feat: ADMIN - mobile gap 추가 및 메인페이지 redirect 추가

- apps/admin/tsconfig.json
- apps/ceos/tsconfig.json
- packages/tsconfig/base.json
- packages/tsconfig/nextjs.json
- packages/ui/tsconfig.json
- packages/utils/tsconfig.json
- tsconfig.base.json
> fix: 빌드 오류 수정

- apps/ceos/src/components/recruit/recruitSubHeader.tsx
- apps/ceos/src/pages/recruit/index.tsx
#76 
- 전형 절차 따라 버튼 정보가 바뀔 수 있도록 해놓았습니다.
- 지원하기 버튼 선택 -> 지원하기 페이지 이동 -> 제출의 플로우를 확인하였습니다.
new Date(날짜 스트링) 으로 string -> Date 변환 시,
해당 날짜의 9시로 변환되어 해당 날짜의 9시까지만 지원을 할 수 있는 에러가 있어 날짜만 반환하는 함수를 따로 만들었습니다.
요건 플로우 확인이 안되는데... @YooSeonHo 확인 부탁드립니다
> refactor: 리크루팅 페이지 검증

- apps/admin/src/pages/applyStatement/index.tsx
- #76 
- 지원현황 pagination이 하드코딩되어있는 부분을 수정했습니다.
> fix: ADMIN - 지원현황 pagination 오류 수정

- apps/ceos/src/pages/project/index.tsx
- apps/ceos/src/pages/recruit/index.tsx
- apps/ceos/src/styles/landing/index.tsx
- packages/ui/src/components/Card/ManagementCard.tsx
#76 
그리드 수정했습니다
가운데 정렬 안 되는 것들이나 자잘한 ui 깨짐 수정했습니다
> fix: CEOS Management 페이지 그리드 수정

- apps/ceos/src/components/GlassBox/index.tsx
- apps/ceos/src/components/Layout/index.tsx
- apps/ceos/src/pages/FAQ/index.tsx
- apps/ceos/src/pages/management/index.tsx
- apps/ceos/src/pages/project/index.tsx
- apps/ceos/src/pages/recruit/docpass/index.tsx
- apps/ceos/src/pages/recruit/finpass/index.tsx
- apps/ceos/src/pages/recruit/index.tsx
> fix: 빌드 에러

- apps/ceos/src/pages/project/index.tsx
> fix: build error

- apps/admin/src/pages/_document.tsx
- apps/ceos/src/pages/_document.tsx
- apps/ceos/src/pages/project/index.tsx
> fix: og image

- apps/admin/src/pages/_document.tsx
- apps/ceos/src/pages/_document.tsx
- apps/ceos/src/pages/project/index.tsx
> feat: master push

- apps/ceos/src/components/Landing/subHeader.tsx
- apps/ceos/src/pages/management/index.tsx
- packages/ui/src/styles/mediaQuery.ts
> fix: Mobile 컴포넌트

- apps/ceos/src/components/project/ProjectCardContainer/index.tsx
- packages/ui/src/components/Card/ActivityCard.tsx
> fix: 사파리 레이아웃 오류 수정

- .pnp.cjs
- .pnp.loader.mjs
- apps/admin/src/components/NonLogin/index.tsx
- apps/admin/src/pages/application/index.tsx
- apps/admin/src/pages/applyStatement/index.tsx
- apps/admin/src/pages/auth/index.tsx
- apps/admin/src/pages/manageUser/index.tsx
- yarn.lock
- 유저관리 페이지 no data 경우 pagination 해결
- 지원서 제출 버튼 쪼그라듦 문제 해결
- 로그인 쿠키 있을 시 로그인안됨 문제 해결 > 로그인하기 버튼 클릭 시 쿠키 삭제
- 면접 시간 지정 서류합격 상태일때만 보이게 수정
> Fix : ADMIN - 세부 오류 수정

- apps/admin/src/components/Layout/index.tsx
- apps/ceos/public/header/activity.svg
- apps/ceos/public/header/faq.svg
- apps/ceos/public/header/project.svg
- apps/ceos/public/header/recruit.svg
- apps/ceos/src/components/Header/index.tsx
- apps/ceos/src/components/MenuBar/index.tsx
- apps/ceos/src/components/recruit/recruitSubHeader.tsx
- packages/ui/src/components/Card/RewardCard.tsx
- #76 
- header 박스 추가
- 카드 애니메이션 추가
- 버튼 레이아웃 오류 수정
- 지원 가능 날짜 계산 수정
- 디폴트로 오전 9시로 잡히는 문제 -> setHour 추가
> fix: CEOS - 레이아웃 수정 및 지원 가능 날짜 계산 로직 오류 수정

- apps/admin/src/pages/project/edit/[[...id]].tsx
- apps/admin/src/pages/reward/add/[[...id]].tsx
- apps/ceos/src/components/project/DetailModal/index.tsx
- #76 
- project 수정 로직 수정 및 유효성 검사 추가
- project modal - 폰트 weight 수정
> fix: ADMIN - 레이아웃 수정

- apps/admin/src/pages/application/index.tsx
- apps/admin/src/pages/faq/index.tsx
- apps/admin/src/pages/project/edit/[[...id]].tsx
- apps/ceos/src/components/GlassBox/index.tsx
- apps/ceos/src/components/Modals/checkModal.tsx
- apps/ceos/src/components/Modals/timeModal.tsx
- apps/ceos/src/components/recruit/interface.tsx
- apps/ceos/src/pages/recruit/index.tsx
- #76 
- modal 레이아웃 깨지는 부분 수정
- 오픈 채팅 링크 이동 추가
- admin - application, faq 등 맡은 파트 레이아웃 깨지는 것 수정
> fix: ADMIN - 일부 레이아웃 깨지는 부분 수정

- apps/ceos/src/pages/recruit/apply/index.tsx
> fix: 지원서 static props 수정

- apps/ceos/src/components/project/DetailModal/index.tsx
- apps/ceos/src/components/recruitModal/ErrorModal.tsx
- apps/ceos/src/components/recruitModal/SubmitModal.tsx
- apps/ceos/src/components/recruitModal/SuccessModal.tsx
- apps/ceos/src/pages/recruit/apply/index.tsx
#76 
- 모달 ref의 위치를 수정하였습니다.
- project 모달의 경우 x 버튼 선택 시에만 모달이 사라지게 수정하였습니다.
> fix: 모달 내부 영역 선택 시 닫히는 이슈

- apps/ceos/src/components/recruitModal/SubmitModal.tsx
> fix : 빌드 에러

- .pnp.cjs
- apps/ceos/src/components/project/DetailModal/index.tsx
- apps/ceos/src/components/recruitModal/SubmitModal.tsx
- packages/ui/package.json
- packages/ui/src/assets/CloseIcon/WhiteCloseIcon.tsx
- packages/ui/src/components/Card/ActivityCard.tsx
- packages/ui/src/components/Card/ProjectCard.tsx
- packages/utils/src/apis/ceos/projectApi.ts
- yarn.lock
> fix: Next Image 적용

- apps/ceos/next.config.js
- apps/ceos/src/components/Layout/index.tsx
- apps/ceos/src/components/recruit/interface.tsx
- apps/ceos/src/hooks/useInfiniteQueries.tsx
- apps/ceos/src/pages/recruit/apply/index.tsx
- apps/ceos/src/pages/recruit/index.tsx
- packages/utils/src/apis/ceos/recruitApi.ts
#76 
next.js 리다이렉트 설정이 문제인가 싶어서, 리다이렉트 부분을 주석처리하고
해당 페이지 접근 시 처음에 지원기간인지 확인 후 루트로 리다이렉트 시키는 로직을 반영하였습니다.
> fix: 리크루팅 접근불가 로직

- apps/admin/src/pages/application/index.tsx
- packages/utils/src/apis/admin/adminApplicationApi.ts
- #76 
- questionId 삭제
- multiline 디폴트 수정
- date 전달 포맷 수정
> fix: ADMIN - 지원서 페이지 수정

- apps/ceos/src/components/project/DetailModal/index.tsx
- apps/ceos/src/pages/recruit/apply/index.tsx
#76 
- 프로젝트 모달 
- 지원서 페이지 내 watch() 제거
> fix: 프로젝트 모달 수정

- apps/ceos/src/components/Layout/index.tsx
- apps/ceos/src/pages/_app.tsx
- packages/ui/src/components/FloatingButton/index.tsx
> fix: project 페이지 모달 떴을 시 floating button 없애기

- apps/ceos/src/assets/landing/glassButtonText.tsx
- apps/ceos/src/components/Landing/buttons.tsx
- apps/ceos/src/components/Landing/rewards.tsx
- apps/ceos/src/components/Landing/sponsor.tsx
- apps/ceos/src/components/Landing/subHeader.tsx
- apps/ceos/src/components/project/DetailModal/index.tsx
- packages/ui/src/components/Button/index.tsx
- packages/ui/src/components/TextField/index.tsx
> fix: 트랜지션, css

- apps/admin/src/components/Layout/index.tsx
- apps/admin/src/components/Modals/interviewTimeModal.tsx
- apps/admin/src/pages/applyStatement/index.tsx
- apps/admin/src/pages/auth/findID/index.tsx
- apps/admin/src/pages/auth/findPW/index.tsx
- apps/admin/src/pages/manageUser/index.tsx
- 지원서 엑셀 다운로드시 발생하는 오류를 수정했습니다. (엑셀 파일 이름 변경)
- 면접 시간 지정 or 변경시 바로 업데이트 되지 않는 오류를 수정했습니다
- cookie가 있는 상태에서 auth 페이지에 접근시 새로운 accestoken 을 받아 auth 페이지에 접근하지 못하도록 했습니다
- 기타 세부적인 오류 alert를 추가했습니다
> Fix: ADMIN - 지원서 엑셀 다운로드 / 면접 시간 업데이트 / 로그인 오류 수정

- apps/admin/src/pages/auth/index.tsx
cookie 있는 경우 auth 페이지에 아이디/비밀번호 로그인 창이 아니라 loading 보이게 수정했습니다
> Fix: ADMIN - cookie 있는 경우 auth 페이지 loading 보이게 수정

- apps/ceos/src/components/MenuBar/index.tsx
- packages/ui/src/styles/GlobalStyles.ts
> fix : 사이드 메뉴바 크기 조정

- apps/admin/src/pages/auth/index.tsx
> Fix : ADMIN - auth 페이지 로직 수정

- apps/ceos/src/components/recruit/Information.tsx
- apps/ceos/src/components/recruit/style/index.tsx
- packages/ui/src/components/Checkbox/index.tsx
> fix: 지원서 모바일 ui

- apps/admin/src/components/reward/RewardCardContainer/index.tsx
- apps/admin/src/pages/reward/add/[[...id]].tsx
- apps/admin/src/pages/reward/index.tsx
- packages/utils/src/apis/admin/adminRewardApi.ts
> fix: reward 추가하기 기능 제거, DTO 변경 반영

- apps/ceos/src/components/project/DetailModal/index.tsx
- apps/ceos/src/components/recruit/Information.tsx
- apps/ceos/src/pages/FAQ/index.tsx
- apps/ceos/src/pages/activity/index.tsx
#76 
- 프로젝트 세부 모달 첫번째 이미지 잘림 이슈
- 세부모달 내 링크 오타 이슈
- 세부모달 X 위치 이슈
- 세부모달 팀원 한명 갭 이슈
- 지원서 질문 중복 이슈
- 각종 대소문자 수정
- 세부모달 90vh 수정
> fix: QA 반영

- apps/admin/src/assets/data/dropDownList.tsx
- apps/admin/src/components/Layout/index.tsx
- apps/admin/src/pages/auth/index.tsx
- packages/utils/src/apis/admin/adminAuthApi.tsx
> Fix : ADMIN - 로그인 오류 해결

- apps/ceos/src/components/project/DetailModal/index.tsx
- apps/ceos/src/components/recruit/Information.tsx
- apps/ceos/src/pages/recruit/apply/index.tsx
#76 
- 지원서 제출 시, 생년월일 & 전화번호를 숫자로 입력시 정해진 형식에 맞춰 변환되도록 작업했습니다.
- 프로젝트 세부모달에서 링크 컴포넌트가 길어질 시, 두 줄로 보이게 했습니다.
- 지원서 그리드가 iOS에서 깨지는 오류가 있어 수정했습니다.
> fix: apply 폼 수정

- apps/ceos/src/assets/logo/index.tsx
- apps/ceos/src/components/Landing/rewards.tsx
- apps/ceos/src/components/Landing/subHeader.tsx
- apps/ceos/src/components/recruit/recruitBox.tsx
- apps/ceos/src/components/recruit/recruitBtn.tsx
- apps/ceos/src/components/recruit/recruitSubHeader.tsx
- apps/ceos/src/pages/recruit/index.tsx
- apps/ceos/src/styles/recruit/index.tsx
> fix: 간격 수정

- apps/ceos/src/components/Landing/sponsor.tsx
- apps/ceos/src/components/Landing/subHeader.tsx
- apps/ceos/src/components/Modals/checkModal.tsx
- apps/ceos/src/components/recruit/docpass/index.tsx
- apps/ceos/src/components/recruit/finpass/index.tsx
- packages/ui/src/components/Card/SponsorCard.tsx
#76 
- 지원 정보 오류 모달 추가
- 스폰서 모바일 수정
- 메인 페이지 전체보기 안눌림 문제 해결
> Fix : 모달 추가 및 버그 수정

- packages/ui/src/components/Card/ActivityCard.tsx
#76 
사파리에서 ActivityCard가 깨지는 현상을 해결하였습니다.
> Fix: Activity QA

- apps/admin/src/components/Layout/index.tsx
- apps/admin/src/pages/auth/index.tsx
> fix: ADMIN - refreshtoken 만료기한 수정 & 로그인 오류 해결

- apps/admin/src/components/Layout/index.tsx
- apps/admin/src/components/Sidebar/index.tsx
- apps/admin/src/pages/auth/index.tsx
- packages/utils/src/apis/admin/adminAuthApi.tsx
> Feat : ADMIN - 로그아웃

- .gitignore
- packages/utils/src/apis/axiosConfig.ts
#181 
.env 사용이 요상하게 안 돼서... config.json으로 빼 뒀습니당
> feat: 서버 도메인 변경 반영

- packages/utils/src/apis/axiosConfig.ts
> feat: 서버 도메인 변경

- .gitignore
- apps/admin/src/assets/Arrow/index.tsx
> fix: gitignore 수정

- apps/ceos/src/pages/management/index.tsx
#76 
- 멘토 없으면 자리 차지 안하도록 수정했습니다.
> fix : 해당 파트 mentor 없을 때 자리 차지 x

- apps/admin/src/pages/management/add/[[...id]].tsx
- apps/admin/src/pages/project/edit/[[...id]].tsx
> feat: validation 수정, admin part 추가

- apps/ceos/src/components/Footer/index.tsx
- apps/ceos/src/components/FooterText/index.tsx
- apps/ceos/src/pages/recruit/apply/index.tsx
- packages/ui/src/components/Card/RewardCard.tsx
> fix: rewardCard, 푸터 연도

- apps/ceos/src/pages/management/index.tsx
> refactor : 멘토 코드 리팩토링

- apps/admin/src/pages/management/add/[[...id]].tsx
> fix: 어드민 management page validation 변경

- apps/admin/src/pages/management/add/[[...id]].tsx
#203
management part에 개발 파트 추가했습니당
> feat: management part 개발 추가

- apps/ceos/src/components/GlassBox/index.tsx
> Fix : 모달 수정

- apps/ceos/src/components/recruit/Schedule.tsx
> fix : 모달 뜨게 수정

- apps/admin/src/components/Modals/applicationModal.tsx
x
admin > 지원현황 > 지원서
문항 답변의 글자 수 표기
> feat: 지원서 맨 뒤에 글자수 표기

- apps/ceos/src/components/project/DetailModal/index.tsx
- apps/ceos/src/components/recruit/Information.tsx
x
프로젝트 하단의 외부 링크 클릭시 새창에서 열리도록함
기타 활동에 재학 여부 텍스트 포함
> Hotfix(ceos)/text fix

- apps/ceos/src/components/Modals/checkModal.tsx
- apps/ceos/src/pages/_document.tsx
- apps/ceos/src/pages/project/index.tsx
- apps/ceos/src/state/index.tsx
- packages/utils/src/apis/axiosConfig.ts
x
SEO 추가 테스트를 위해 _document.js에 관련 meta tag 추가
jennifer frontend(에러 추적 툴)(링크)[https://front.jennifersoft.com/#/app/6f42c908/dashboard/overview] 관련 메타 태그 추가
---
Work In Progress
Project 페이지 내 scroll 기능 구현중
> 담부터 이슈 발행해서 할게요 봐주세요

- apps/admin/src/pages/applyStatement/index.tsx
- packages/utils/src/apis/admin/adminApplyStatementApi.tsx
지원자 이름 입력 후 검색버튼이나 엔터누르면 검색 결과 나오도록 했습니다.
> feat(admin)/searching

- apps/admin/src/assets/data/dropDownList.tsx
- apps/admin/src/components/Dropdown/index.tsx
- apps/admin/src/components/Layout/index.tsx
- apps/admin/src/components/Sidebar/index.tsx
- apps/admin/src/pages/applyStatement/index.tsx
- apps/admin/src/pages/auth/index.tsx
- apps/admin/src/utils/dropdown.ts
- packages/utils/src/apis/admin/adminApplyStatementApi.tsx
- 페이지 선택 후 해당 페이지 까지 데이터가 없는 필터를 선택할 때 페이지 찾지 못하는 이슈
- 로그아웃 시 깜빡임 이슈
- 기타 등등
- 선택 안함 필터링 추가
- 로그아웃 시 깜빡임 이슈 해결
- 로그인,토큰,쿠키 관련 useEffect 수정
- 필터링 시 페이지 초기화
> feat(admin)/hotfix

- apps/admin/src/pages/recruit/index.tsx
admin 페이지 datePicker time error
해결!
> Hofix(admin)/time error

- apps/admin/src/components/Sidebar/index.tsx
- apps/admin/src/pages/application/index.tsx
> Feat(admin)/fix

- apps/ceos/src/pages/recruit/index.tsx
> fix: recruit제출 00시에는 전날 날짜 나오도록 수정

- apps/ceos/src/components/Footer/index.tsx
- apps/ceos/src/components/FooterText/index.tsx
- apps/ceos/src/pages/recruit/apply/index.tsx
> fix: 년도 수정

- apps/admin/src/assets/Sidebar/index.tsx
- apps/admin/src/components/DataGrid/Pagination.tsx
- apps/admin/src/components/DataGrid/index.tsx
- apps/admin/src/components/Dropdown/index.tsx
- apps/admin/src/components/Layout/index.tsx
- apps/admin/src/components/Sidebar/index.tsx
- apps/admin/src/pages/applyStatement/index.tsx
X
admin 지원현황 페이지에서 창 크기 줄이면 아예 안 보이는 상태라 반응형 가능하게 수정했습니다.
1. 사이드바 토글 가능하게 수정.
2. 지원현황 페이지 PC, 모바일 반응형 가능하게 수정.
사이드바 토글 버튼의 경우 디자인 피드백 없이 간단하게 만든 거라 추후 수정 요청 들어오면 수정 보도록 하겠습니다!
그리고 반응형 도입하면서 다른 페이지에서 깨짐으로 큰 불편함 있는지 확인 부탁드립니다...^^
제가 확인했을 때는 잘리는 부분 없었던 관계로 PR 날립니다!
> feat : admin 지원현황 페이지 반응형 주가

- apps/admin/src/components/Modals/applicationModal.tsx
- apps/ceos/src/components/recruit/recruitSubHeader.tsx
- 제출한 지원서 줄바꿈 인식할 수 있도록 수정
- 파트별 질문 1번 문항 중복되는 현상 수정 ( 대신 'oo 파트 질문'으로 표시 )
> Fix(admin)/apply doc

- apps/admin/src/components/DataGrid/index.tsx
- apps/admin/src/components/Layout/index.tsx
- apps/admin/src/components/Sidebar/index.tsx
- apps/admin/src/pages/applyStatement/index.tsx
사이드 바 펼쳤을 때도 화면 가려지지 않게 width 수정하였습니다.
피고 닫을 때 width 애니메이션 추가하였습니다!
https://github.com/user-attachments/assets/2c1a36e5-641b-489d-b45e-a9845c5139e8
> fix : 반응형 width 단위로 수정

- apps/ceos/src/components/Modals/emailModal.tsx
- apps/ceos/src/components/recruit/recruitSubHeader.tsx
- apps/ceos/src/pages/recruit/index.tsx
- packages/utils/src/apis/ceos/emailApi.ts
리크루팅 전 메일링 서비스 구현
- 이메일 폼 모달 구현
- 이메일 API 연결
> Feat(ceos)/email

- apps/ceos/src/components/recruit/recruitSubHeader.tsx
- 기수 숫자 하드코딩(20) => {generation}으로 수정
> chore: 버튼 기수 숫자=>{generation}으로 수정

- apps/admin/src/components/DataGrid/index.tsx
- apps/admin/src/components/Layout/index.tsx
- apps/admin/src/components/Sidebar/index.tsx
Reverts CEOS-Developers/CEOS-FE#231
> Revert "fix : 반응형 width 단위로 수정"

- apps/ceos/src/components/recruit/recruitSubHeader.tsx
Reverts CEOS-Developers/CEOS-FE#234
> Revert "chore: 버튼 기수 숫자=>{generation}으로 수정"

- apps/ceos/src/components/recruit/recruitSubHeader.tsx
Reverts CEOS-Developers/CEOS-FE#236
> Revert "Revert "chore: 버튼 기수 숫자=>{generation}으로 수정""

- apps/ceos/src/components/recruit/recruitSubHeader.tsx
Reverts CEOS-Developers/CEOS-FE#237
> Revert "Revert "Revert "chore: 버튼 기수 숫자=>{generation}으로 수정"""

- apps/ceos/src/components/Modals/emailModal.tsx
- apps/ceos/src/components/recruit/recruitSubHeader.tsx
> fix: helperText type error

- apps/admin/src/components/DataGrid/index.tsx
- apps/admin/src/components/Layout/index.tsx
- apps/admin/src/components/Sidebar/index.tsx
Reverts CEOS-Developers/CEOS-FE#235
> fix: admin 반응형 width 단위로 수정

- .pnp.cjs
- apps/ceos/src/pages/FAQ/index.tsx
- apps/ceos/src/state/index.tsx
- package.json
- yarn.lock
- 기존에 매 기수마다 하드코딩으로 바꿨던 generation을 recoilvalue 이용해 전역변수로 수정
> fix: generation 하드코딩 -> 전역변수설정

- apps/ceos/src/pages/FAQ/index.tsx
> hotfix: 불필요한 코드 제거

- apps/ceos/src/components/Footer/index.tsx
- footer copyright 문구 하드코딩에서 현재 년도까지로 표기되게 수정
> fix: footer copyright year 자동화

- apps/admin/src/components/DataGrid/Pagination.tsx
- apps/admin/src/components/DataGrid/index.tsx
페이지네이션 아래 부분에 margin 값 없는 부분 수정 간단히 했습니다!
> chore : margin 값 수정

- apps/admin/src/components/Sidebar/index.tsx
- apps/admin/src/pages/applyStatement/index.tsx
- toggle btn 위치 수정
- 생성일시 text margin값 줘서 검색버튼과 거리 수정
> Hotfix(ceos)/admin ui fix

- apps/admin/src/pages/applyStatement/index.tsx
- apps/admin/src/pages/recruit/index.tsx
- packages/utils/src/apis/admin/sendEmailApi.ts
- packages/utils/src/apis/axiosConfig.ts
- 등록된 이메일 전송 버튼 없음
- baseUrl 환경변수 설정
> Feat(admin)/root feature

- apps/ceos/src/components/recruit/Schedule.tsx
- apps/ceos/src/pages/recruit/apply/index.tsx
- packages/ui/src/components/common/Wrapper.tsx
- 대면 면접이 추가되어 면접날짜 선택 문구 수정하였습니다.
- 면접 가능 시간 기존 14:00-20:00에서 10:00-20:00으로 수정하였습니다. 체크박스가 많아짐에 따라 아래 사진처럼 한 줄이 아닌 두 줄로 표시하였습니다.
> Feat(ceos): 면접 가능 시간 추가 및 디자인 수정

- apps/ceos/src/components/GlassBox/index.tsx
> Fix(ceos): 파트 별 안내사항 Text 인터뷰 -> 면접
